### ISSUE TITLE
Could you provide how you made .UF2 files for your example projects?

### ISSUE THREAD

**Issue by liudr** [Seeed-Studio/Seeed_Arduino_USBDISP#7]
Hi,

I think this is a valid feature request to add documentation of how to create .UF2 file from arduino. Because it involves a number of steps to make this project work, including installing Arduino IDE, adding Seeed SAMD boards, adding the project files and possibly some libraries if I didn't download them already from trying out other Seeed boards and projects.
I'd like to know how to generate .UF2 files so I can send the .UF2 to someone who has no knowledge of the above but can still enjoy the Wio terminal. I added some keyboard/mouse features so it would be a nice operating panel for RPI without KMV.

Thank you!

**Comment by LynnL4** [comment]
Hi

**Comment by LynnL4** [comment]
Hi,

**Comment by LynnL4** [comment]
Hi,

**FYI**

## Converting bin to uf2 for SAMD21

1. Download the [**Microsoft uf2 tool**](https://github.com/microsoft/uf2) from the official site to your local drive:

```sh
$ git clone https://github.com/microsoft/uf2.git
```

2. Navigate to the `utils` folder:

```sh
$ cd uf2/utils
```

1. Run the **`uf2conv.py`** python script in this location as follow:

```sh
$ python uf2conv.py -f 0x68ed2b88 -b 0x2000 [bin path] -o flash.uf2
# For example: for SAMD21(Cortex M0: XIAO, Seeeduino Zero, etc)
# python uf2conv.py -f 0x68ed2b88 -b 0x2000 /Users/ansonhe/Desktop/blink.bin -o flash.uf2
# or for SAMD51(Cortex M4: wio terminal, etc)
# python uf2conv.py -f 0x55114460 -b 0x4000 /Users/ansonhe/Desktop/blink.bin -o flash.uf2
```

**Note:** `-f 0x68ed2b88` is for SAMD21 and `-b 0x2000` is used for base address.
**Note:** `-f 0x55114460` is for SAMD51 and `-b 0x4000 ` is used for base address.

4. Now you should find the converted `flash.uf2` appeared in the **`uf2/utils`** folder.

5. Simply drag the `flash.uf2` into the Arduino Bootloader.

**Comment by EdXian** [comment]
Hi @LynnL4 ,
I try to use arm-none-eabi-gcc to build the code and convert the generated code to .uf2 by
`python uf2conv.py -f 0x68ed2b88 -b 0x2000 example.bin -o flash.uf2`  .
 Finally, I got a flash.uf2 and drag it to USB MSC . However, the usb device exit and didnt run my application. 
I had tested my board with arduino and it can run example easily.
here is my [projects](https://github.com/EdXian/arm-cortexm-cmake-template/tree/Ed/Example/xiao) which is the simplest project to startup samd21.

**Comment by LynnL4** [comment]
Hi EdXian:
https://github.com/EdXian/arm-cortexm-cmake-template/blob/e895d73f3ced8cc7a568b2be8afc2091ac0e90ff/Example/samd21/samd21g18a_flash.ld#L39
https://github.com/Seeed-Studio/ArduinoCore-samd/blob/28c4ac5980a0393f7417c773c5d8fa4f5283b379/variants/XIAO_m0/linker_scripts/gcc/flash_with_bootloader.ld#L28
When you use the uf2 bootloader, you need to reserve 8K(SAMD21) of memory for it.  So, you need to change the script of ld

**Comment by EdXian** [comment]
Hi @LynnL4 
Thank you for your help. I'll try it!
